angular.module('partials', [])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/jobs.html', [
'',
'<div ng-controller="JobsController" class="jobs">',
'  <form ng-submit="findJobs()" class="form-horizontal">',
'    <div class="control-group">',
'      <label class="control-label">Skills</label>',
'      <div class="controls">',
'        <input type="text" ng-model="skills" class="span4">',
'      </div>',
'    </div>',
'    <div class="control-group">',
'      <label class="control-label">Type</label>',
'      <div class="controls">',
'        <select multiple="multiple" ng-model="type" class="input-medium">',
'          <option>Hourly</option>',
'          <option>Fixed</option>',
'        </select>',
'      </div>',
'    </div>',
'    <div class="control-group">',
'      <div class="controls">',
'        <button type="submit" class="btn btn-large btn-primary input-large">',
'          <i class=\'icon-search\'></i>',
'          Find',
'        </button>',
'      </div>',
'    </div>',
'  </form>',
'  <div class="results">',
'    <div class="item">',
'      <div class="badges"><span class="badge">Fixed</span><span>&nbsp;</span><span class="badge badge-success">100$</span><span>&nbsp;</span><span class="badge badge-info">less 1 week</span><a href="#" class="btn btn-warning btn-mini pull-right">',
'          <i class=\'icon-share-alt\'></i>',
'          Go</a></div>',
'      <div class="description">I have source code for an iOS slot machine game. I am looking to ‘reskin’ the game entirely by replacing symbol design, buttons, sounds, and an ‘unlock payout’ screen which is used to facilitate in-app purchases. \n\nI am looking for a contract with a fixed price, not an hourly wage. This is non-negotiable. \n\n\nThe resource folder contains approximately 30 graphics. I have a specific idea of what I want for many of the images – however there are several where I am open to ...</div>',
'    </div>',
'    <div class="item">',
'      <div class="badges"><span class="badge">Hourly</span><span>&nbsp;</span><span class="badge badge-success">40$/h</span><span>&nbsp;</span><span class="badge badge-info">more 6 monthes</span><a href="#" class="btn btn-warning btn-mini pull-right">',
'          <i class=\'icon-share-alt\'></i>',
'          Go</a></div>',
'      <div class="description">I have source code for an iOS slot machine game. I am looking to ‘reskin’ the game entirely by replacing symbol design, buttons, sounds, and an ‘unlock payout’ screen which is used to facilitate in-app purchases ...</div>',
'    </div>',
'    <div class="item">',
'      <div class="badges"><span class="badge">Fixed</span><span>&nbsp;</span><span class="badge badge-success">100$</span><span>&nbsp;</span><span class="badge badge-info">less 1 week</span><a href="#" class="btn btn-warning btn-mini pull-right">',
'          <i class=\'icon-share-alt\'></i>',
'          Go</a></div>',
'      <div class="description">I have source code for an iOS slot machine game. I am looking to ‘reskin’ the game entirely by replacing symbol design ...</div>',
'    </div>',
'  </div>',
'  <ul class="pager">',
'    <li class="previous"><a href="#">&larr; Older</a></li>',
'    <li class="next disabled"><a href="#">Newer &rarr;</a></li>',
'  </ul>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/nav.html', [
'',
'<ul class="nav">',
'  <li ng-class="getClass(\'/jobs\')"><a ng-href="#/jobs">',
'      <i class=\'icon-briefcase\'></i>',
'      Jobs</a></li>',
'</ul>',''].join("\n"));
}]);