angular.module('partials', [])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/jobs.html', [
'',
'<div ng-controller="JobsController" class="jobs">',
'  <div class="row">',
'    <div class="columns small-centered small-11">',
'      <form ng-submit="findJobs()" class="panel">',
'        <div class="row">',
'          <div class="columns small-12">',
'            <div class="row">',
'              <div class="columns small-3">',
'                <label class="right inline">Skills</label>',
'              </div>',
'              <div class="columns small-9">',
'                <input type="text" ng-model="skills">',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'        <div class="row">',
'          <div class="columns small-12">',
'            <div class="row">',
'              <div class="columns small-3">',
'                <label class="right inline">Type</label>',
'              </div>',
'              <div class="columns left small-5">',
'                <select ng-model="type">',
'                  <option value="">None</option>',
'                  <option>Hourly</option>',
'                  <option>Fixed</option>',
'                </select>',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'        <div class="row">',
'          <div class="columns small-8 small-centered">',
'            <button type="submit" class="button expand radius success">',
'              <i class=\'icon-search\'></i>',
'              Find',
'            </button>',
'          </div>',
'        </div>',
'      </form>',
'    </div>',
'  </div>',
'  <div class="results">',
'    <div ng-repeat="jobSearchResult in results" class="item">',
'      <div class="labels"><a ng-href="{{ jobSearchResult.link }}" ng-click="jobSearchResult.go()" class="button small radius right">',
'          <i class=\'icon-share-alt\'></i>',
'          Go</a><span class="label label-inverse">{{ jobSearchResult.type }}</span><span ng-show="jobSearchResult.budget" class="label success">{{ jobSearchResult.budget }}</span><span ng-show="jobSearchResult.busy" class="label alert">{{ jobSearchResult.busy }}</span><span ng-show="jobSearchResult.time" class="label secondary">{{ jobSearchResult.time }}</span></div>',
'      <div class="description">{{ jobSearchResult.description }}</div>',
'    </div>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/nav.html', [
'',
'<ul class="nav">',
'  <li ng-class="getClass(\'/jobs\')"><a ng-href="#/jobs">',
'      <i class=\'icon-briefcase\'></i>',
'      Jobs</a></li>',
'</ul>',''].join("\n"));
}]);